name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      actions: read
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io jq

      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: n0sync
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Kolkata
